name: ðŸ“¦ Publish cy-utilities

on:
  push:
    branches:
      - main
    paths:
      - 'app/cy-utilities/package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: setup bun
        uses: oven-sh/setup-bun@v1

      - name: install dependencies
        run: bun install

      - name: build
        run: bun run build

      - name: testing
        run: bun run test
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if version changed
        id: check_version
        run: |
          VERSION_CHANGED=$(git diff HEAD^ HEAD -- 'app/cy-utilities/package.json' | grep '"version":' || true)
          if [ -z "$VERSION_CHANGED" ]; then
            echo "Version has not changed. Skipping..."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Version has changed. Running job..."
            echo "skip=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: setup node
        if: ${{ env.skip == 'false' }}
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: setup bun
        if: ${{ env.skip == 'false' }}
        uses: oven-sh/setup-bun@v1

      - name: install dependencies
        if: ${{ env.skip == 'false' }}
        run: bun install

      - name: build
        if: ${{ env.skip == 'false' }}
        run: bun run build

      - name: registry
        if: ${{ env.skip == 'false' }}
        run: npm set registry=https://registry.npmjs.org/

      - name: publish
        if: ${{ env.skip == 'false' }}
        run: |
          cd app/cy-utilities
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
